#label_replace(
  #(toxiproxy_proxy_real_connection_duration_seconds_sum / toxiproxy_proxy_real_connection_duration_seconds_count) * 1000,
  #"connection_type", "real", "", ""
#)
#or
#label_replace(
  #(toxiproxy_proxy_connection_duration_seconds_sum / toxiproxy_proxy_connection_duration_seconds_count) * 1000,
  #"connection_type", "total", "", ""
#)
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'your-app'
    static_configs:
      - targets: ['127.0.0.1:8474']  # Adjust port as needed
    metrics_path: '/metrics'
    scrape_interval: 5s
